# Generated by Django 4.1.1 on 2022-09-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='text',
            new_name='comm',
        ),
    ]
