# Generated by Django 4.1.1 on 2022-10-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_text_commentmodel_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='post',
            new_name='pro',
        ),
    ]
