# Generated by Django 4.1.1 on 2022-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_post_commentmodel_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
